@startuml
    App -> NewExpense :Data is generated here
    App -> Expenses :Data is needed here
    
    NewExpense -> ExpenseForm : User's input form

    Expenses --> Card : UI
    Expenses ->ExpenseItem : Every expense item is listed here
    Expenses ->ExpensesFilter : Filter by year

    ExpenseItem --> Card : UI
    ExpenseItem -> ExpenseDate : Every expense's date

@enduml